- name: Install deps
  run: pip install requests

- name: Build merged VLESS list
  run: python merge_vless.py

- name: Commit changes
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add vless_normal_vpn.txt
    git commit -m "auto smart merge vless" || exit 0
    git push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add vless_normal_vpn.txt
          git commit -m "auto update vless" || exit 0
          git push
