- uses: actions/checkout@v4
  with:
    fetch-depth: 0

- run: pip install requests beautifulsoup4

- run: python fetch_vless.py

- run: |
    git config --global user.name "bot"
    git config --global user.email "bot@users.noreply.github.com"

    git add output/vless_eu.txt
    git commit -m "auto update" || echo "no changes"
    git push origin HEAD:main
